services:
  engine: &engine-service
    image: ${ENGINE_IMAGE}
    container_name: control-plane-engine
    hostname: engine
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: "no"
    env_file:
    - engine-config.env
    - ../elasticsearch/es-config.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://engine:8080/api/engine/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - ibm-webmethods-api-management
  engine-debug:
    <<: *engine-service
    env_file:
    - engine-config.env
    - engine-config.debug.env
    - ../elasticsearch/es-config.env
    ports:
    - ${ENGINE_PUBLISH_PORT}:8080

  engine-secure-es:
    <<: *engine-service
    volumes:
    - es-certs:/usr/share/elasticsearch/config/certs