apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.engine.name }}-svc
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: {{ .Values.applications.engine.name }}
  type: ClusterIP
---