services:
  asset-catalog: &asset-catalog-service
    image: ${ASSETCATALOG_IMAGE}
    container_name: control-plane-asset-catalog
    hostname: asset-catalog
    depends_on:
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: "no"
    env_file:
    - asset-catalog-config.env
    - ../elasticsearch/es-config.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://asset-catalog:8080/api/assetcatalog/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - softwareag-api-management
  asset-catalog-debug:
    <<: *asset-catalog-service
    env_file:
    - asset-catalog-config.env
    - asset-catalog-config.debug.env
    - ../elasticsearch/es-config.env
    ports:
    - ${ASSETCATALOG_PUBLISH_PORT}:8080

  asset-catalog-secure-es:
    <<: *asset-catalog-service
    volumes:
    - es-certs:/usr/share/elasticsearch/config/certs
