services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch
    hostname: ${ELASTICSEARCH_HOST}
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 2G
          cpus: '1'
      restart_policy:
        condition: "unless-stopped"
    ports:
    - ${ELASTICSEARCH_PUBLISH_PORT}:9200
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    - node.name=webmethods
    - cluster.name=webmethods
    - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
    - es-data:/usr/share/elasticsearch/data
    networks:
    - ibm-webmethods-api-management
