version: '3.8'
services:
  nginx:
    extends:
      file: nginx/nginx.yaml
      service: nginx
    depends_on:
      ingress:
        condition: service_healthy
  nginx_setup:
    extends:
      file: nginx/nginx.yaml
      service: nginx_setup
  ingress:
    extends:
      file: ingress/ingress.yaml
      service: ingress
    depends_on:
      engine:
        condition: service_healthy
      asset-catalog:
        condition: service_healthy
      ui:
        condition: service_healthy
    environment:
      - server.forward-headers-strategy=NATIVE
  ui:
    extends:
      file: ui/ui.yaml
      service: ui
    depends_on:
      engine:
        condition: service_healthy
      asset-catalog:
        condition: service_healthy
  engine:
    extends:
      file: engine/engine.yaml
      service: engine
    depends_on:
      asset-catalog:
        condition: service_healthy
  asset-catalog:
    extends:
      file: asset-catalog/asset-catalog.yaml
      service: asset-catalog
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    extends:
      file: elasticsearch/elasticsearch.yaml
      service: elasticsearch
  jaeger-tracing:
    extends:
      file: jaeger-tracing/jaeger-tracing.yaml
      service: jaeger-tracing

volumes:
  es-data:
    driver: local
  nginx-certs:
    driver: local
  conf.d:
    driver: local

networks:
  ibm-webmethods-api-management:
    name: ibm-webmethods-api-management
    driver: bridge