services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    depends_on:
      ingress:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: "on-failure"
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - conf.d:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
    networks:
      - softwareag-api-management


  nginx_setup:
    image: nginx
    container_name: nginx_setup
    volumes:
      - nginx-certs:/usr/share/certs
      - conf.d:/usr/share/conf.d
    user: "0"
    command: >
      bash -c '
      openssl req -x509 -nodes -days 9999 -newkey rsa:2048  -subj "${NGINX_CER_SUBJECT}/CN=localhost" -keyout /usr/share/certs/${NGINX_DOMAIN_NAME}.key -out /usr/share/certs/${NGINX_DOMAIN_NAME}.crt
      &&
      echo "
         server {
             server_name ${NGINX_DOMAIN_NAME};
             listen 80 ;
             location / {
                 proxy_pass http://ingress:8080;
                 proxy_set_header X-Forwarded-Proto http;
                 proxy_set_header Host ${NGINX_DOMAIN_NAME};
                 proxy_set_header X-Forwarded-Port ${NGINX_HTTP_PORT};
             }
         }
         server {
           server_name ${NGINX_DOMAIN_NAME};
            listen 443 ssl http2 ;
             ssl_session_timeout 5m;
             ssl_session_cache shared:SSL:50m;
             ssl_session_tickets off;
             ssl_certificate /etc/nginx/certs/${NGINX_DOMAIN_NAME}.crt;
             ssl_certificate_key /etc/nginx/certs/${NGINX_DOMAIN_NAME}.key;
             location / {
                 proxy_pass http://ingress:8080;
                 proxy_set_header X-Forwarded-Proto https;
                 proxy_set_header Host ${NGINX_DOMAIN_NAME};
                 proxy_set_header X-Forwarded-Port ${NGINX_HTTPS_PORT};
             }
         }
      " > /usr/share/conf.d/default.conf
      '
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - softwareag-api-management